"""
Django settings for barometre project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import sys
from pathlib import Path

from django.contrib.messages import constants as messages
from django.urls import reverse_lazy

from . import settings_local

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = settings_local.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = settings_local.DEBUG
ROLE = settings_local.ROLE

# HOST is the canonical name for this host.  This is only needed for
# celery, as requests must use request.get_host().
HOST = settings_local.HOST
# Celery settings.
CELERY_TIMEZONE = "UTC"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_BROKER_URL = "amqp://localhost"
# ## If we want results, we'd have to add one of these two lines:
# CELERY_RESULT_BACKEND = 'django-db'
# CELERY_RESULT_BACKEND = settings_local.CELERY_RESULT_BACKEND
# ## and do: pip install django-celery-results
#
# ## Some settings that copilot suggested.
# CELERY_RESULT_BACKEND = 'django-db'
# CELERY_ACCEPT_CONTENT = ["json"]
# CELERY_TASK_SERIALIZER = "json"
# CELERY_RESULT_SERIALIZER = "json"
# CELERY_TASK_ALWAYS_EAGER = settings_local.CELERY_TASK_ALWAYS_EAGER
# CELERY_TASK_EAGER_PROPAGATES = settings_local.CELERY_TASK_EAGER_PROPAGATES
# CELERY_TASK_DEFAULT_QUEUE = settings_local.CELERY_TASK_DEFAULT_QUEUE
# CELERY_TASK_ROUTES = settings_local.CELERY_TASK_ROUTES
# CELERY_TASK_CREATE_MISSING_QUEUES = True
# CELERY_TASK_DEFAULT_EXCHANGE = "barometre"
# CELERY_TASK_DEFAULT_EXCHANGE_TYPE = "direct"
# CELERY_TASK_DEFAULT_ROUTING_KEY = "barometre"
# CELERY_TASK_QUEUES = settings_local.CELERY_TASK_QUEUES
# CELERY_TASK_DEFAULT_RATE_LIMIT = "10/m"
# CELERY_TASK_SOFT_TIME_LIMIT = 30 * 60


ALLOWED_HOSTS = settings_local.ALLOWED_HOSTS
# This only seems to matter on the barometre host, not when proxying
# through staging.  It avoids CSRF conflicts with the host (due to
# http/https?).
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# This is a list of trusted origins for CSRF protection.
# https://docs.djangoproject.com/en/4.1/ref/settings/#csrf-trusted-origins
# It defaults to an empty list, but you may add your own origins in dev
# using settings_local.py. This allows you to use ngrok or similar.
# Ngrok allows you to open a tunnel and make accessible your local dev branch
# through a browser, notably to make sure it displays well and works on
# your phone before even pushing to beta.
# It avoids too many pushes to beta that may affect the database and require
# a restore.
# see https://ngrok.com/ for usage.
if DEBUG and ROLE == "dev":
    CSRF_TRUSTED_ORIGINS = (
        getattr(settings_local, "CSRF_TRUSTED_ORIGINS", None) or []
    )

# Requirement for Django-debug-toolbar
# https://django-debug-toolbar.readthedocs.io/en/latest/installation.html#configure-internal-ips
# https://github.com/robhudson/django-debug-toolbar
INTERNAL_IPS = [
    "127.0.0.1",
    "localhost",
]
# When running in dev from vagrant, we listen on all interfaces in
# order to port-forward through to the browser.
if DEBUG:
    INTERNAL_IPS = INTERNAL_IPS + ["0.0.0.0"]
    if "INTERNAL_IPS" in settings_local.__dict__:
        INTERNAL_IPS = INTERNAL_IPS + settings_local.INTERNAL_IPS

USE_X_FORWARDED_HOST = True

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "compressor",
    "crispy_forms",
    "crispy_bootstrap5",
    #
    "debug_toolbar",
    #
    # "authentication",
    "core",
    "dashboard",
] + settings_local.MORE_INSTALLED_APPS

# AUTH_USER_MODEL = "authentication.BarometreUser"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if ROLE in ("staging", "qa", "production"):
    MIDDLEWARE += [
        "rollbar.contrib.django.middleware.RollbarNotifierMiddleware",
    ]

ROOT_URLCONF = "barometre.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.role",
            ],
        },
    },
]

CRISPY_TEMPLATE_PACK = "bootstrap5"
CRISPY_FAIL_SILENTLY = not DEBUG

WSGI_APPLICATION = "barometre.wsgi.application"

MESSAGE_TAGS = {
    messages.INFO: "text-info",
    50: "critical",
}


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASES = settings_local.DATABASES


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth"
        ".password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth"
        ".password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth"
        ".password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth"
        ".password_validation.NumericPasswordValidator",
    },
]

AWS_SES_ACCESS_KEY_ID = settings_local.AWS_SES_ACCESS_KEY_ID
AWS_SES_SECRET_ACCESS_KEY = settings_local.AWS_SES_SECRET_ACCESS_KEY
AWS_ACCESS_KEY_ID = settings_local.AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY = settings_local.AWS_SECRET_ACCESS_KEY
AWS_DEFAULT_REGION = settings_local.AWS_DEFAULT_REGION
AWS_SES_REGION_ENDPOINT_URL = "email.eu-central-1.amazonaws.com"
DEFAULT_FROM_EMAIL = "noreply@mobilitains.fr"
AWS_SES_CONFIGURATION_SET_NAME = getattr(
    settings_local, "AWS_SES_CONFIGURATION_SET_NAME", "placeholder123"
)

if "test" in sys.argv:
    # Don't send mail when testing.
    EMAIL_BACKEND = "django.core.mail.backends.locmem.EmailBackend"
    # Force Celery tasks to execute immediately, bypassing the broker,
    # which doesn't run when testing.
    CELERY_TASK_ALWAYS_EAGER = True
    # Ensure that exceptions in tasks are raised in the same process.
    CELERY_TASK_EAGER_PROPAGATES = True
elif "EMAIL_BACKEND" in settings_local.__dict__:
    EMAIL_BACKEND = settings_local.EMAIL_BACKEND
elif ROLE == "dev":
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "django_amazon_ses.EmailBackend"


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "formatters": {
        "django.server": {
            "()": "django.utils.log.ServerFormatter",
            "format": (
                "[{asctime}] {levelname} [{filename}:{lineno}"
                " ({module}:{funcName})]"
                " {message}"
            ),
            "style": "{",
        },
        "django.ses.extra": {
            "()": "django.utils.log.ServerFormatter",
            "format": (
                "[{asctime}] {levelname}[{filename}:{lineno} ({funcName})]"
                " {message} Notification : {notification}"
            ),
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "filters": ["require_debug_true"],
            "class": "logging.StreamHandler",
            "formatter": "django.server",
        },
        "django.server": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "django.server",
        },
        "mail_admins": {
            "level": "ERROR",
            "filters": ["require_debug_false"],
            "class": "django.utils.log.AdminEmailHandler",
        },
        "web": {
            "level": "INFO",
            # 'class': 'logging.handlers.TimedRotatingFileHandler',
            "class": "logging.FileHandler",
            "filename": settings_local.LOG_DIR + "barometre.log",
            "formatter": "django.server",
            # 'when': 'd',
            # 'utc': True,
            # 'backupCount': 10,
        },
        "celery": {
            "level": "INFO",
            # "class": "logging.handlers.TimedRotatingFileHandler",
            "class": "logging.FileHandler",
            "filename": settings_local.LOG_DIR + "celery.log",
            "formatter": "django.server",
            # "when": "midnight",
            # "interval": 1,
            # "backupCount": 10,
            # "utc": True,
        },
        "stripe": {
            "level": "INFO",
            # "class": "logging.handlers.TimedRotatingFileHandler",
            "class": "logging.FileHandler",
            "filename": settings_local.LOG_DIR + "stripe.log",
            "formatter": "django.server",
            # "when": "midnight",
            # "interval": 1,
            # "backupCount": 10,
            # "utc": True,
        },
        "django_ses_notification": {
            "level": "INFO",
            # 'class': 'logging.handlers.TimedRotatingFileHandler',
            "class": "logging.FileHandler",
            "filename": settings_local.LOG_DIR + "barometre-ses.log",
            "formatter": "django.ses.extra",
            # 'when': 'd',
            # 'utc': True,
            # 'backupCount': 10,
        },
        "gcp_handler": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": settings_local.LOG_DIR + "gcp.log",
            "formatter": "django.server",
        },
    },
    "loggers": {
        "app": {
            # 'handlers': ['console', 'mail_admins'],
            "handlers": ["django.server", "mail_admins"],
            "level": "INFO",
            "propagate": True,
        },
        "django": {
            # 'handlers': ['console', 'mail_admins'],
            "handlers": ["console", "web", "mail_admins"],
            "level": "INFO",
            "propagate": True,
        },
        "django.server": {
            "handlers": ["console", "django.server", "mail_admins"],
            "level": "INFO",
            "propagate": False,
        },
        "celery": {
            "handlers": ["console", "celery"],
            "level": "INFO",
            "propagate": True,
        },
        "stripe": {
            "handlers": ["console", "stripe"],
            "level": "INFO",
            "propagate": True,
        },
        "django_ses": {
            "handlers": ["console", "django_ses_notification", "mail_admins"],
            "level": "INFO",
            "propagate": True,
        },
        "gcp": {
            "handlers": ["console", "gcp_handler"],
            "level": "INFO",
            "propagate": True,
        },
    },
}

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

# The default is two weeks.
seconds_in_week = 60 * 60 * 24 * 7
SESSION_COOKIE_AGE = seconds_in_week * 26

LANGUAGE_CODE = "fr-fr"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True
LOGIN_REDIRECT_URL = "index"
LOGIN_URL = reverse_lazy("authentication:login")
# LOGOUT_REDIRECT_URL = 'index'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = settings_local.STATIC_URL
STATIC_ROOT = settings_local.STATIC_ROOT

# Prefix for uploaded files. Must be different from static_url
MEDIA_URL = settings_local.MEDIA_URL
# Directory where uploaded files are stored
MEDIA_ROOT = settings_local.MEDIA_ROOT

# Define this for nginx contexts.
if "STATIC_ROOT" in dir(settings_local):
    STATIC_ROOT = settings_local.STATIC_ROOT

# FileSystemFinder and AppDirectoriesFinder are enabled by default.
STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "compressor.finders.CompressorFinder",
)

CAPTCHA_NOISE_FUNCTIONS = ("captcha.helpers.noise_arcs",)
CAPTCHA_CHALLENGE_FUNCT = "captcha.helpers.random_char_challenge"
CAPTCHA_LENGTH = 7
# Set this to true if testing.
CAPTCHA_TEST_MODE = "test" in sys.argv

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

if ROLE in ("staging", "qa", "production"):
    import os

    ROLLBAR = {
        "access_token": settings_local.ROLLBAR_ACCESS_TOKEN,
        "environment": "dev" if DEBUG else "production",
        "root": os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    }
    import rollbar

    rollbar.init(**ROLLBAR)

STRIPE_PUBLISHABLE_KEY = settings_local.STRIPE_PUBLISHABLE_KEY
STRIPE_SECRET_KEY = settings_local.STRIPE_SECRET_KEY
STRIPE_ENDPOINT_SECRET = settings_local.STRIPE_ENDPOINT_SECRET
STRIPE_LIVE_MODE = (ROLE == "production") and settings_local.STRIPE_LIVE_MODE

if "test" in sys.argv:
    MIGRATION_MODULES = {"tlc": "tlc.test_unique_mixin"}
