# Generated by Django 5.1.7 on 2025-09-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_alter_observation_observed_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
                ("commune", models.CharField(max_length=10)),
                ("epci", models.CharField(max_length=12)),
                ("departement", models.CharField(max_length=3)),
                ("region", models.CharField(max_length=3)),
            ],
        ),
        migrations.RenameModel(
            old_name="GeoPoint",
            new_name="Commune",
        ),
        migrations.RenameField(
            model_name="observation",
            old_name="geopoint",
            new_name="commune",
        ),
    ]
