# Generated by Django 5.1.7 on 2025-09-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_mappoint_rename_geopoint_commune_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commune",
            name="year",
            field=models.CharField(default="2025", max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mappoint",
            name="map_name",
            field=models.CharField(default="2021", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mappoint",
            name="year",
            field=models.CharField(default="2021", max_length=4),
            preserve_default=False,
        ),
    ]
