# Generated by Django 5.1.7 on 2025-09-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_commune_year_mappoint_map_name_mappoint_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="mappoint",
            name="import_filename",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="mappoint",
            name="import_id",
            field=models.CharField(default="", max_length=16),
        ),
        migrations.AddConstraint(
            model_name="mappoint",
            constraint=models.UniqueConstraint(
                fields=(
                    "year",
                    "map_name",
                    "longitude",
                    "latitude",
                    "commune",
                ),
                name="unique_mappoint",
            ),
        ),
    ]
